name: Open App with self hosted runner

on: [push]

jobs:
  open:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker Compose
      run: docker-compose up --build -d
